con = -1;
marker_objects = [];
marker_sprites = [];
marker_exceptions = [3596, 5118, 2242, 1416];
snowflakes = [];
snowflakes_start = false;
snowflakes_stop = false;
snowflakes_stop_fast = false;
vent_tiles = layer_tilemap_get_id(layer_get_id("TILES_Vents"));
