EVENT = 0;
TIMER = 0;
HEARTMADE = 0;
HSINER = 0;
OBMADE = 0;
global.flag[20] = 0;
global.flag[6] = 1;
global.typer = 667;
scr_windowcaption(scr_84_get_lang_string("DEVICE_FAILURE_slash_Create_0_gml_10_0"));
FADEFACTOR = 0;
WHITEFADE = 0;
FADEUP = 0;
DARK_WAIT = 0;
